#!/bin/bash
function parse_git_dirty {

  [[ $(git status 2> /dev/null | tail -n1) != "无文件要提交，干净的工作区" ]] && echo "*"
}
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}





export PS1="\[\033[01;31m\]\u\[\033[00m\]@\[\033[01;32m\]\h\[\033[00m\]:\\
\[\033[01;34m\]\w\[\033[00m\] \\
\[\e[0m\]git:(\[\033[01;31m\]$(parse_git_branch)\[\e[0m\])\n$"
